### ISSUE TITLE
Can you add instagram reels support too ? 

### ISSUE THREAD

**Issue by rsoorajs** [gentritabazi01/DoInsta#1]
current code supports only instagram links like this 👇

`https://www.instagram.com/p/CGhI1OUDhNs/?igshid=hrih6mrix2wt`

but now the default links of reels and igtv is like

`https://www.instagram.com/reel/CGhI1OUDhNs/?igshid=hrih6mrix2wt` 

`https://www.instagram.com/tv/CGhI1OUDhNs/?igshid=hrih6mrix2wt`

These urls are not working in your current code,so please add support for these type of urls too.
i know changing `reels` and `tv`  to `p` will work,but its hard for noob users..so please fix it

Thanks in advance

**Comment by gentritabazi** [comment]
@telegrambotdev check this:

https://github.com/gentritabazi01/DoInsta/releases/tag/1.0.0
